### ISSUE TITLE
Can't load BERTweet Tokenizer

### ISSUE THREAD

**Issue by TamHHM** [VinAIResearch/BERTweet#18]
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")

results in:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tam/anaconda3/lib/python3.8/site-packages/transformers/tokenization_auto.py", line 220, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/tam/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1425, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/tam/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1524, in _from_pretrained
    raise EnvironmentError(
OSError: Model name 'vinai/bertweet-base' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed 'vinai/bertweet-base' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

transformers version: 3.1.0

**Comment by datquocnguyen** [comment]
Please install `transformers` version 3.3+ or install it from the source:
    
    git clone https://github.com/huggingface/transformers.git
    cd transformers
    pip3 install --upgrade .

And also clean/remove  your `transformers` folder in `~/.cache/torch`, so it'd automatically re-download BERTweet properly.
